# Exclude doc starter pack (but keep .md, .rst)
exclude: '^docs/(doc-cheat-sheet.*|(?!.+\.(md|rst)).+)|hatch_build.py|yarf/lib/wayland/protocols/.*|yarf/vendor/.*$'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    exclude: ^docs/.*\.md$
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.22
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
    - mdformat-gfm
    - mdformat-myst

- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort

# To run `mypy` meaningfully, we need all dependencies,
# and run it on all files.
#
# Ref.: https://github.com/python/mypy/issues/13916
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    language: system
    pass_filenames: false
    args:
    - --check-untyped-defs
    - --ignore-missing-imports  # Ref.: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
    - --exclude
    - tests/.*
    - --exclude
    - docs/.*
    - --exclude
    - hatch_build.py
    - --exclude
    - yarf/vendor/.*
    - .

- repo: https://github.com/MarketSquare/robotframework-tidy
  rev: 4.16.0
  hooks:
  - id: robotidy
    args:
    - --configure
    - RenameTestCases:enabled=true
    - --configure
    - RenameVariables:enabled=true
    - --configure
    - IndentNestedKeywords:enabled=true
    - --configure
    - AlignKeywordsSection:enabled=true
    - --configure
    - AlignTestCasesSection:enabled=true
    - --configure
    - AlignTemplatedTestCases:enabled=true

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.0
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format

- repo: https://github.com/PyCQA/docformatter
  rev: eb1df347edd128b30cd3368dddc3aa65edcfac38 # Don't autoupdate until https://github.com/PyCQA/docformatter/issues/293 is fixed
  hooks:
  - id: docformatter
    args: [
      --in-place,
      --pre-summary-newline,
      --make-summary-multi-line,
    ]

- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
  - id: interrogate
    exclude: 'tests/.*'
    args: [
      --verbose,
      --fail-under=61.8,
    ]

- repo: https://github.com/jsh9/pydoclint.git
  rev: 0.6.2
  hooks:
  - id: pydoclint
    exclude: 'tests/.*'
    args: [
      --style=google,
      --skip-checking-short-docstrings=False,
      --arg-type-hints-in-docstring=False,
      --check-return-types=False,
      --check-yield-types=False,
      --baseline=pydoclint-baseline.txt,
      # --generate-baseline=True,
    ]
  - id: pydoclint
    files: 'tests/.*'
    args: [
      --style=google,
      --skip-checking-short-docstrings=True,
      --arg-type-hints-in-docstring=False,
      --check-return-types=False,
      --check-yield-types=False,
    ]

- repo: local
  hooks:
    - id: licensecheck
      name: licensecheck
      entry: uv tool run licensecheck --zero --show-only-failing --requirements-paths=pyproject.toml
      language: system
      pass_filenames: false
