name: yarf-example-plugin
base: core24
version: '0.0.1'
summary: YARF example plugin library
description: |
  A Python library providing a YARF-compatible example plugin,
  shared via a content interface.

grade: stable
confinement: strict

plugs:
  # The example plugin requires this plug to share
  # the content of platform plugins directory with YARF
  platform-plugins:
    interface: content
    target: $SNAP_COMMON/platform_plugins

parts:
  yarf-example:
    plugin: python
    source: .
    python-packages:
      - .
    build-packages:
      - git
      - pkg-config
      - libxkbcommon-dev
      - libwayland-dev
    stage-packages:
      - libxkbcommon0
      - bash
    # We use an override-build step to copy the onboard-plugin script
    # to $SNAP_PART_INSTALL/bin so that it ends up in $SNAP/bin
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp bin/onboard-plugin $CRAFT_PART_INSTALL/bin/onboard-plugin

apps:
  # the onboard-plugin app runs the onboard-plugin script
  # so that the example plugin will be copied to the shared
  # platform-plugins directory, where YARF can find it
  # when it is run.
  onboard-plugin:
    command: bin/onboard-plugin
    plugs:
      - platform-plugins
