name: yarf-example-plugin
base: core24
version: '0.0.1'
summary: YARF example plugin library
description: |
  A Python library providing a YARF-compatible example plugin,
  shared via a content interface.

grade: stable
confinement: strict

plugs:
  platform-plugins:
    interface: content
    target: $SNAP_COMMON/platform_plugins

parts:
  yarf-example:
    plugin: python
    source: .
    python-packages:
      - .
    stage-packages:
      - bash
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp bin/onboard-plugin $CRAFT_PART_INSTALL/bin/onboard-plugin

apps:
  onboard-plugin:
    command: bin/onboard-plugin
    plugs:
      - platform-plugins
