name: yarf
base: core24
adopt-info: yarf
summary: Yet Another Robot Framework
description: |
  Yet Another Robot Framework (YARF) is an interface that
  allows developers to build complex test scenarios and
  bootstrap them locally, then work towards automated runs.

grade: stable
confinement: strict

parts:
  scripts:
    plugin: dump
    source: scripts

  yarf:
    plugin: python
    source: .
    build-packages:
      - pkg-config
      - libwayland-dev
      - libxkbcommon-dev
    build-snaps:
      - yq
    stage-packages:
      - ffmpeg
      - libpulse0
      - libblas3
      - liblapack3
      - libice6
      - libgl1
      - libsm6
      - libxkbcommon0
      - tesseract-ocr
      - xkb-data
    override-pull: |
      craftctl default
      craftctl set version=$(yq -r .project.version pyproject.toml)
    organize:
      usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pulseaudio/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}

environment:
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

apps:
  yarf:
    command-chain:
      - bin/wayland-launch
    command: bin/yarf
    plugs:
      - home
      - network
      - wayland
