name: yarf
base: core24
adopt-info: yarf
summary: Yet Another Robot Framework
description: |
  Yet Another Robot Framework (YARF) is an interface that
  allows developers to build complex test scenarios and
  bootstrap them locally, then work towards automated runs.

grade: stable
confinement: strict

parts:
  scripts:
    plugin: dump
    source: scripts

  yarf:
    plugin: python
    source: .
    build-snaps:
      - yq
    stage-packages:
      - ffmpeg
      - libblas3
      - liblapack3
      - tesseract-ocr
    override-pull: |
      craftctl default
      craftctl set version=$(yq -r .project.version pyproject.toml) || true
    override-stage: |
      TESSDATA_DIR=$(find "$CRAFT_PART_INSTALL/usr/share/tesseract-ocr" -type d -name tessdata)
      TESSVER_DIR=$(dirname "$TESSDATA_DIR")
      mv "$TESSDATA_DIR" $(dirname "$TESSVER_DIR")
      rm -r "$TESSVER_DIR"

      craftctl default

    build-environment:
      # TODO: Drop this when this goes in:
      #  https://github.com/canonical/snapcraft/pull/5514
      - C_INCLUDE_PATH: /snap/gnome-46-2404-sdk/current/usr/include:${C_INCLUDE_PATH:-}

    organize:
      usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}

apps:
  yarf:
    extensions:
      - gnome
    command-chain:
      - bin/wayland-launch
    command: bin/yarf
    plugs:
      - home
      - network
    environment:
      TESSDATA_PREFIX: "$SNAP/usr/share/tesseract-ocr/tessdata"
