name: yarf
base: core24
adopt-info: yarf
summary: Yet Another Robot Framework
description: |
  Yet Another Robot Framework (YARF) is an interface that
  allows developers to build complex test scenarios and
  bootstrap them locally, then work towards automated runs.

grade: stable
confinement: strict

layout:
  /usr/share/tesseract-ocr:
    bind: $SNAP/usr/share/tesseract-ocr
  /usr/share/ffmpeg:
    bind: $SNAP/usr/share/ffmpeg
  /usr/lib/python3.12/tkinter:
    bind: $SNAP/usr/lib/python3.12/tkinter
  /usr/lib/python3.12/lib-dynload/_tkinter.cpython-312-$CRAFT_ARCH_TRIPLET_BUILD_FOR.so:
    symlink: $SNAP/usr/lib/python3.12/lib-dynload/_tkinter.cpython-312-$CRAFT_ARCH_TRIPLET_BUILD_FOR.so
  /usr/lib/tcltk:
    bind: $SNAP/usr/lib/tcltk
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk

parts:
  scripts:
    plugin: dump
    source: scripts

  yarf:
    plugin: python
    source: .
    build-snaps:
      - yq
    stage-packages:
      - ffmpeg
      - libblas3
      - liblapack3
      - tesseract-ocr
      - python3-tk
      - xclip
    override-pull: |
      craftctl default
      craftctl set version=$(yq -r .project.version pyproject.toml) || true

    build-environment:
      # TODO: Drop this when this goes in:
      #  https://github.com/canonical/snapcraft/pull/5514
      - C_INCLUDE_PATH: /snap/gnome-46-2404-sdk/current/usr/include:${C_INCLUDE_PATH:-}

    organize:
      usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}

    prime:
      - -etc/X11
      - -etc/fonts
      - -usr/share/drirc.d
      - -usr/share/X11
      - -usr/share/lintian
      - -usr/share/man

  cleanup:
    after: [ yarf ]
    plugin: nil
    build-snaps: [core24, mesa-2404, gnome-46-2404 ]
    override-prime: |
      set -eux

      # Go through the pre-requisite snaps of this snap and drop the relevant
      # duplicate files, in particular:
      #  - All the libraries (any so-version) that we ship in content snaps
      #  - All the "usr" files that are already part of the content snaps
      for snap in "core24" "mesa-2404" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec sh -c 'rm -fv "$CRAFT_PRIME/{}"*' \;
        cd "/snap/$snap/current" && find usr -type f,l -exec rm -fv "$CRAFT_PRIME/{}" \;
      done

      find "$CRAFT_PRIME" -type d -empty -delete

apps:
  yarf:
    extensions:
      - gnome
    command-chain:
      - bin/wayland-launch
    command: bin/yarf
    plugs:
      - home
      - network
      - process-control
