name: yarf
base: core22
adopt-info: yarf
summary: Yet Another Robot Framework
description: |
  Yet Another Robot Framework (YARF) is an interface that 
  allows developers to build complex test scenarios and 
  bootstrap them locally, then work towards automated runs.

grade: devel
confinement: strict

parts:
  yarf:
    plugin: python
    source: .
    build-snaps:
      - yq
    override-pull: |
      craftctl default
      craftctl set version=$(yq -r .project.version pyproject.toml)


apps:
  yarf:
    command: bin/yarf
