name: yarf
base: core22
adopt-info: yarf
summary: Yet Another Robot Framework
description: |
  Yet Another Robot Framework (YARF) is an interface that
  allows developers to build complex test scenarios and
  bootstrap them locally, then work towards automated runs.

grade: devel
confinement: strict

parts:
  scripts:
    plugin: dump
    source: scripts

  yarf:
    plugin: python
    source: .
    build-packages:
      - pkg-config
      - libwayland-dev
    build-snaps:
      - yq
    stage-packages:
      - libice6
      - libgl1
      - libsm6
      - tesseract-ocr
    override-pull: |
      craftctl default
      craftctl set version=$(yq -r .project.version pyproject.toml)


apps:
  yarf:
    command-chain:
    - bin/wayland-launch
    command: bin/yarf
    plugs:
      - home
      - network
      - wayland
