name: Main Documentation Checks

on:
  pull_request:
    paths:
      - docs/**
      - yarf/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    runs-on: [self-hosted-linux-amd64-jammy-large]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y \
            git-lfs \
            libgl1 \
            libxkbcommon-dev \
            jq \
            clang \
            python3-tk

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.12

      - name: Spell Check
        id: spellcheck-step
        if: success() || failure()
        uses: canonical/documentation-workflows/spellcheck@12ec83203d373adf3f6a8fef6ef1f0e3db8dadcb
        with:
          working-directory: 'docs/'
          install-target: 'install'
          spelling-target: 'spelling'
          makefile: 'use-default'

      - name: Inclusive Language Check
        id: woke-step
        if: success() || failure()
        uses: canonical/documentation-workflows/inclusive-language@1f5b0900b9c570021f35101ddf0456c70994db0e
        with:
          working-directory: 'docs/'
          install-target: 'install'
          woke-target: 'woke'
          makefile: 'use-default'

      - name: Link Check
        id: linkcheck-step
        if: success() || failure()
        uses: canonical/documentation-workflows/linkcheck@9e1646051a7c99df3c347304122308a5d517e065
        with:
          working-directory: 'docs/'
          install-target: 'install'
          woke-target: 'linkcheck'
          makefile: 'use-default'
