name: Main Documentation Checks

on:
  pull_request:
    paths:
      - docs/**
      - yarf/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    runs-on: [self-hosted-linux-amd64-jammy-large]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y \
            git-lfs \
            libgl1 \
            libxkbcommon-dev \
            jq \
            clang

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Spell Check
        id: spellcheck-step
        if: success() || failure()
        uses: canonical/documentation-workflows/spellcheck@main
        with:
          working-directory: 'docs/'
          install-target: 'install'
          spelling-target: 'spelling'
          makefile: 'use-default'

      - name: Inclusive Language Check
        id: woke-step
        if: success() || failure()
        uses: canonical/documentation-workflows/inclusive-language@main
        with:
          working-directory: 'docs/'
          install-target: 'install'
          woke-target: 'woke'
          makefile: 'use-default'

      - name: Link Check
        id: linkcheck-step
        if: success() || failure()
        uses: canonical/documentation-workflows/linkcheck@main
        with:
          working-directory: 'docs/'
          install-target: 'install'
          woke-target: 'linkcheck'
          makefile: 'use-default'
