name: PR Validation
permissions:
  contents: read
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  validate_title:
    runs-on: ubuntu-latest
    steps:
    - name: Checking the presence of the traceability tag in the PR title
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        echo "$PR_TITLE" | awk '
        /^\[(New|Breaking|Infra|BugFix)\]/ {
            print "Starts with a recognized tag"
            exit 0
        }
        {
            print "No recognized traceability tag"
            print "Please start the PR title with one of the following tags: [New], [Breaking], [Infra], [BugFix]"
            print "e.g. [New] $PR_TITLE"
            exit 1
        }'
