name: PR Validation
permissions:
  contents: read
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  validate_title:
    runs-on: ubuntu-latest
    steps:
    - name: Checking the presence of the traceability tag in the PR title
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        error_msg() {
            title=$(sed -E ':a; s/^(\[[[:alnum:]_-]+]?[[:space:]]*|[[:alnum:]_-]+][[:space:]]*)//; ta' <<< "$PR_TITLE")
            echo "No recognized traceability tag / there are multiple tags"
            echo "Please start the PR title with one of the following tags: [New], [Breaking], [Infra], [BugFix]"
            echo "e.g. [New] $title"
        }

        if echo "$PR_TITLE" | grep -Eq '^\[(New|Breaking|Infra|BugFix)\]'; then
            count=$(grep -o '\[[^]]\+\]' <<< "$PR_TITLE" | wc -l)
            if [ "$count" -eq 1 ]; then
                echo "Traceability tag found."
                exit 0
            else
                error_msg
                exit 1
            fi
        else
            error_msg
            exit 1
        fi
