name: PR Validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

permissions:
  contents: read

concurrency:
  group: pr-validation-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate_title:
    runs-on: ubuntu-latest
    steps:
    - name: Checking the presence of the traceability tag in the PR title
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        error_msg() {
            title=$(printf '%s' "$PR_TITLE" | sed -E \
                -e 's/\[[^]]*\]?[[:space:]]*//g' \
                -e 's/(^|[[:space:]])[^[:space:]]*\][[:space:]]*/\1/g' \
                -e 's/\][[:space:]]*//g' \
                -e 's/[[:space:]]+/ /g' \
                -e 's/^[[:space:]]+//; s/[[:space:]]+$//')
            echo "No recognized traceability tag / there are multiple tags"
            echo "Please start the PR title with one of the following tags: [New], [Breaking], [Infra], [BugFix]"
            echo "e.g. [New] $title"
        }

        if echo "$PR_TITLE" | grep -Eq '^\[(New|Breaking|Infra|BugFix)\]'; then
            count=$(grep -o '\[[^]]\+\]' <<< "$PR_TITLE" | wc -l)
            if [ "$count" -eq 1 ]; then
                echo "Traceability tag found."
                exit 0
            else
                error_msg
                exit 1
            fi
        else
            error_msg
            exit 1
        fi
