name: "Build YARF snap: Dry Run"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PEP 440 compliant version string'
        required: true
        type: string
      commit_sha:
        description: 'Commit SHA to build from'
        required: true
        type: string
      commit_short_sha:
        description: 'Commit SHA to build from'
        required: true
        type: string

run-name: "Build version: ${{ inputs.version }} (${{ inputs.commit_short_sha }})"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}

      - uses: astral-sh/setup-uv@v3

      - name: Set version
        run: uv version "${{ inputs.version }}" --frozen

      - name: Upload updated pyproject.toml
        uses: actions/upload-artifact@v4
        with:
          name: updated-pyproject
          path: pyproject.toml

  build_amd64:
    needs: set-version
    runs-on: [self-hosted, linux, noble, x64, large]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.commit_sha }}

    - name: Download updated pyproject.toml
      uses: actions/download-artifact@v4
      with:
        name: updated-pyproject
        path: .

    - uses: canonical/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79
      id: snapcraft
    - uses: actions/upload-artifact@v4
      with:
        name: yarf-amd64
        path: ${{ steps.snapcraft.outputs.snap }}

  build_arm64:
    needs: set-version
    runs-on: [self-hosted, linux, noble, arm64, large]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.commit_sha }}

    - name: Download updated pyproject.toml
      uses: actions/download-artifact@v4
      with:
        name: updated-pyproject
        path: .

    - uses: canonical/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79
      id: snapcraft
    - uses: actions/upload-artifact@v4
      with:
        name: yarf-arm64
        path: ${{ steps.snapcraft.outputs.snap }}
