name: Test snap builds without errors

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - .github/workflows/test-snap-build.yaml
      - snap/**
      - pyproject.toml
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build snap on ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runs_on: ubuntu-24.04
          - arch: arm64
            runs_on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs_on }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Build snap
      uses: canonical/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79

    - name: Upload snap artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: ${{ matrix.arch }}-snap
        path: "*.snap"
        if-no-files-found: error
        retention-days: 5
