name: TICS Code Quality Analysis
on:
  schedule:
    - cron: '00 19 * * *'
  workflow_dispatch:

permissions:
  contents: read  # Required to check out repository code

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    name: Run TICS analysis
    runs-on: [self-hosted-linux-amd64-noble-tiobe]
    steps:
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
            sudo apt update -qq
            sudo apt install -y \
            git-lfs \
            libgl1 \
            libxkbcommon-dev \
            jq \
            clang \
            python3-tk

            pip install \
            coverage \
            flake8 \
            pylint \
            pytest \
            pyfakefs \
            uv \
            --break-system-packages

      - name: Checkout repo (main branch)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: main
          lfs: true
          fetch-depth: 0
          persist-credentials: false

      - name: Install YARF
        run: |
          pip install .

      - name: Run test and coverage
        run: |
          uv --no-managed-python venv --system-site-packages
          uv sync
          uv run pytest -n=auto --cov=yarf --cov-fail-under=100 --cov-report term-missing
          coverage xml

      - name: Rename coverage report for TICS
        run: |
          mkdir ./coverage
          mv ./coverage.xml ./coverage/cobertura.xml

      - name: Export PATH for TICS
        run: echo PATH=$PATH >> $GITHUB_ENV

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@333078bc527399e5916a166bd1a3a788be5a01a9
        with:
          mode: qserver
          project: yarf
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          calc: ALL
